#!/bin/csh -f
# ../../cool/bin/lexer $* | ./parser $* | ../../cool/bin/semant $* | ../../cool/bin/cgen $*
../Lab\ 01\ -\ Building\ the\ Lexical\ Analyzer/lexer $* | ./parser $* | ../../cool/bin/semant $* | ../../cool/bin/cgen $*
